import React from "react";
import {
  Shield,
  FileText,
  Database,
  Users,
  Lock,
  AlertTriangle,
  Mail,
  Phone,
  MapPin,
  Calendar,
  ChevronRight,
  Eye,
  Settings,
  Share2,
  Globe,
  UserCheck,
  Trash2,
} from "lucide-react";
import * as Accordion from "@radix-ui/react-accordion";
import ContactUsButton from "@/components/ContactUsButton";
import Footer from "@/components/Footer";

const PrivacyPolicy: React.FC = () => {
  const sections = [
    {
      id: "overview",
      title: "Overview",
      icon: <Shield className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="text-gray-700 leading-relaxed">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
            and use of information in accordance with this Privacy Policy.
          </p>
          <div className="bg-blue-50 border-l-4 border-[#FF7A00] p-4 rounded-r-lg">
            <p className="text-sm text-gray-700">
              <strong>Your Privacy Matters:</strong> We are committed to protecting your personal information and being transparent about how we collect, use, and share your data.
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "definitions",
      title: "Interpretation and Definitions",
      icon: <FileText className="w-5 h-5" />,
      content: (
        <div className="space-y-6">
          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">Interpretation</h3>
            <p className="text-gray-700 leading-relaxed">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The
              following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
          </div>
          
          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-4">Definitions</h3>
            <div className="grid gap-4">
              {[
                { term: "Account", definition: "A unique account created for You to access our Service or parts of our Service." },
                { term: "Affiliate", definition: "An entity that controls, is controlled by or is under common control with a party." },
                { term: "Application", definition: "Refers to Boookbox, the software program provided by the Company." },
                { term: "Company", definition: "Refers to Renown Commodity Trading, 23 Pat-coll drive Lagos." },
                { term: "Country", definition: "Refers to Nigeria." },
                { term: "Device", definition: "Any device that can access the Service such as a computer, a cellphone or a digital tablet." },
                { term: "Personal Data", definition: "Any information that relates to an identified or identifiable individual." },
                { term: "Service", definition: "Refers to the Application." },
                { term: "Service Provider", definition: "Any natural or legal person who processes the data on behalf of the Company." },
                { term: "Third-party Social Media Service", definition: "Any website or social network website through which a User can log in or create an account to use the Service." },
                { term: "Usage Data", definition: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself." },
                { term: "You", definition: "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service." },
              ].map((item, index) => (
                <div key={index} className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                  <h4 className="font-semibold text-[#FF7A00] mb-2">{item.term}:</h4>
                  <p className="text-gray-700 text-sm">{item.definition}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      ),
    },
    {
      id: "data-collection",
      title: "Collecting and Using Your Personal Data",
      icon: <Database className="w-5 h-5" />,
      content: (
        <div className="space-y-6">
          <div className="bg-[#FF7A00]/10 border border-[#FF7A00]/20 rounded-lg p-4">
            <h3 className="text-lg font-semibold text-gray-800 mb-3 flex items-center">
              <UserCheck className="w-5 h-5 text-[#FF7A00] mr-2" />
              Personal Data
            </h3>
            <p className="text-gray-700 mb-3">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include:
            </p>
            <ul className="text-gray-700 space-y-1">
              <li>• Email address</li>
              <li>• First name and last name</li>
              <li>• Phone number</li>
              <li>• Address, State, Province, ZIP/Postal code, City</li>
            </ul>
          </div>
          
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h3 className="text-lg font-semibold text-gray-800 mb-3 flex items-center">
              <Eye className="w-5 h-5 text-blue-600 mr-2" />
              Usage Data
            </h3>
            <p className="text-gray-700 mb-3">
              Usage Data is collected automatically when using the Service and may include:
            </p>
            <ul className="text-gray-700 space-y-1 text-sm">
              <li>• Your Device's Internet Protocol address (IP address)</li>
              <li>• Browser type and version</li>
              <li>• Pages of our Service that You visit</li>
              <li>• Time and date of Your visit</li>
              <li>• Time spent on pages</li>
              <li>• Unique device identifiers</li>
            </ul>
          </div>
          
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <h3 className="text-lg font-semibold text-gray-800 mb-3 flex items-center">
              <Share2 className="w-5 h-5 text-green-600 mr-2" />
              Third-Party Social Media Services
            </h3>
            <p className="text-gray-700 mb-3">
              You can create an account and log in through:
            </p>
            <div className="flex flex-wrap gap-2">
              {["Google", "Facebook", "Instagram", "Twitter", "LinkedIn"].map((service) => (
                <span key={service} className="bg-white border border-green-300 text-green-700 px-3 py-1 rounded-full text-sm">
                  {service}
                </span>
              ))}
            </div>
          </div>
        </div>
      ),
    },
    {
      id: "data-usage",
      title: "Use of Your Personal Data",
      icon: <Settings className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed mb-4">
            The Company may use Personal Data for the following purposes:
          </p>
          <div className="grid gap-4">
            {[
              { icon: <Settings className="w-4 h-4" />, title: "Service Provision", description: "To provide and maintain our Service, including monitoring usage." },
              { icon: <UserCheck className="w-4 h-4" />, title: "Account Management", description: "To manage Your registration and provide access to Service functionalities." },
              { icon: <FileText className="w-4 h-4" />, title: "Contract Performance", description: "Development and compliance of purchase contracts for products or services." },
              { icon: <Mail className="w-4 h-4" />, title: "Communication", description: "To contact You regarding updates, notifications, and service information." },
              { icon: <Globe className="w-4 h-4" />, title: "Marketing", description: "To provide news, special offers, and information about similar services." },
              { icon: <Users className="w-4 h-4" />, title: "Request Management", description: "To attend and manage Your requests to Us." },
            ].map((item, index) => (
              <div key={index} className="flex items-start p-4 bg-gray-50 rounded-lg border border-gray-200">
                <div className="text-[#FF7A00] mr-3 mt-0.5">
                  {item.icon}
                </div>
                <div>
                  <h4 className="font-semibold text-gray-800 mb-1">{item.title}</h4>
                  <p className="text-gray-700 text-sm">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      ),
    },
    {
      id: "data-sharing",
      title: "Sharing Your Personal Information",
      icon: <Share2 className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed mb-4">
            We may share Your personal information in the following situations:
          </p>
          <div className="space-y-3">
            {[
              "With Service Providers to monitor and analyze the use of our Service",
              "For business transfers during mergers, acquisitions, or asset sales",
              "With Affiliates, requiring them to honor this Privacy Policy",
              "With business partners to offer certain products, services or promotions",
              "With other users when You interact in public areas",
              "With Your explicit consent for any other purpose",
            ].map((item, index) => (
              <div key={index} className="flex items-start">
                <ChevronRight className="w-4 h-4 text-[#FF7A00] mr-2 mt-0.5 flex-shrink-0" />
                <p className="text-gray-700 text-sm">{item}</p>
              </div>
            ))}
          </div>
        </div>
      ),
    },
    {
      id: "data-retention",
      title: "Retention of Your Personal Data",
      icon: <Database className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to comply with legal obligations, resolve disputes, and enforce our agreements.
          </p>
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <h4 className="font-semibold text-yellow-800 mb-2 flex items-center">
              <AlertTriangle className="w-4 h-4 mr-2" />
              Usage Data Retention
            </h4>
            <p className="text-sm text-yellow-700">
              Usage Data is generally retained for shorter periods, except when used to strengthen security, improve functionality, or when legally required for longer periods.
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "data-transfer",
      title: "Transfer of Your Personal Data",
      icon: <Globe className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            Your information, including Personal Data, is processed at the Company's operating offices and other locations where processing parties are located. This may involve transfer to computers outside Your jurisdiction.
          </p>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="font-semibold text-blue-800 mb-2 flex items-center">
              <Lock className="w-4 h-4 mr-2" />
              Security Commitment
            </h4>
            <p className="text-sm text-blue-700">
              The Company will take all reasonable steps to ensure Your data is treated securely and in accordance with this Privacy Policy.
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "data-deletion",
      title: "Delete Your Personal Data",
      icon: <Trash2 className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            You have the right to delete or request assistance in deleting Personal Data We have collected about You.
          </p>
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <h4 className="font-semibold text-green-800 mb-2">Your Rights</h4>
            <ul className="text-sm text-green-700 space-y-1">
              <li>• Delete certain information through your account settings</li>
              <li>• Update, amend, or delete Your information</li>
              <li>• Request access to, correct, or delete personal information</li>
            </ul>
          </div>
          <p className="text-gray-700 text-sm">
            <strong>Note:</strong> We may need to retain certain information when we have a legal obligation to do so.
          </p>
        </div>
      ),
    },
    {
      id: "security",
      title: "Security of Your Personal Data",
      icon: <Lock className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.
          </p>
          <div className="bg-red-50 border border-red-200 rounded-lg p-4">
            <h4 className="font-semibold text-red-800 mb-2 flex items-center">
              <AlertTriangle className="w-4 h-4 mr-2" />
              Security Notice
            </h4>
            <p className="text-sm text-red-700">
              While we strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "children-privacy",
      title: "Children's Privacy",
      icon: <UserCheck className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
            <h4 className="font-semibold text-orange-800 mb-2">Age Restriction</h4>
            <p className="text-sm text-orange-700 mb-2">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.
            </p>
            <p className="text-sm text-orange-700">
              If you are a parent or guardian and believe your child has provided us with Personal Data, please contact us immediately.
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "external-links",
      title: "Links to Other Websites",
      icon: <Globe className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <p className="text-sm text-yellow-700">
              <strong>Disclaimer:</strong> We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>
          </div>
        </div>
      ),
    },
    {
      id: "policy-changes",
      title: "Changes to this Privacy Policy",
      icon: <FileText className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="font-semibold text-blue-800 mb-2">Notification Methods</h4>
            <ul className="text-sm text-blue-700 space-y-1">
              <li>• Email notification</li>
              <li>• Prominent notice on Our Service</li>
              <li>• Updated "Last updated" date</li>
            </ul>
          </div>
          <p className="text-gray-700 text-sm">
            You are advised to review this Privacy Policy periodically for any changes.
          </p>
        </div>
      ),
    },
    {
      id: "contact",
      title: "Contact Us",
      icon: <Mail className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-gray-700 leading-relaxed mb-4">
            If you have any questions about this Privacy Policy, You can contact us through:
          </p>
          <div className="grid md:grid-cols-2 gap-4">
            <div className="bg-[#FF7A00]/10 border border-[#FF7A00]/20 rounded-lg p-4">
              <div className="flex items-center mb-3">
                <Mail className="w-5 h-5 text-[#FF7A00] mr-2" />
                <h4 className="font-semibold text-gray-800">Email</h4>
              </div>
              <a 
                href="mailto:officialboookbox@gmail.com"
                className="text-[#FF7A00] hover:text-[#FF7A00]/80 transition-colors"
              >
                officialboookbox@gmail.com
              </a>
            </div>
            <div className="bg-[#FF7A00]/10 border border-[#FF7A00]/20 rounded-lg p-4">
              <div className="flex items-center mb-3">
                <Phone className="w-5 h-5 text-[#FF7A00] mr-2" />
                <h4 className="font-semibold text-gray-800">Phone</h4>
              </div>
              <div className="space-y-1">
                <p className="text-gray-700">+234 814 245 4106</p>
                <p className="text-gray-700">+234 706 581 3394</p>
              </div>
            </div>
          </div>
          <div className="bg-[#FF7A00]/10 border border-[#FF7A00]/20 rounded-lg p-4">
            <div className="flex items-center mb-3">
              <MapPin className="w-5 h-5 text-[#FF7A00] mr-2" />
              <h4 className="font-semibold text-gray-800">Address</h4>
            </div>
            <p className="text-gray-700">
              RENOWN COMMODITY TRADING<br />
              23 Pat-coll Drive<br />
              Lagos, Nigeria
            </p>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-gradient-to-r from-[#FF7A00] to-[#FF7A00]/80 text-white py-16">
        <div className="max-w-4xl mx-auto px-4">
          <div className="flex items-center mb-4">
            <Shield className="w-8 h-8 mr-3" />
            <h1 className="text-4xl font-bold">Privacy Policy</h1>
          </div>
          <div className="flex items-center text-orange-100">
            <Calendar className="w-4 h-4 mr-2" />
            <p className="text-lg">Last updated: May 29, 2025</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          <Accordion.Root type="single" collapsible className="w-full">
            {sections.map((section) => (
              <Accordion.Item key={section.id} value={section.id} className="border-b last:border-b-0">
                <Accordion.Header>
                  <Accordion.Trigger className="flex w-full items-center justify-between p-6 text-left hover:bg-gray-50 transition-colors group">
                    <div className="flex items-center">
                      <div className="text-[#FF7A00] mr-3">
                        {section.icon}
                      </div>
                      <h2 className="text-lg font-semibold text-gray-800 group-hover:text-[#FF7A00] transition-colors">
                        {section.title}
                      </h2>
                    </div>
                    <ChevronRight className="w-5 h-5 text-gray-400 group-hover:text-[#FF7A00] transition-all group-data-[state=open]:rotate-90" />
                  </Accordion.Trigger>
                </Accordion.Header>
                <Accordion.Content className="px-6 pb-6 data-[state=open]:animate-slideDown data-[state=closed]:animate-slideUp overflow-hidden">
                  {section.content}
                </Accordion.Content>
              </Accordion.Item>
            ))}
          </Accordion.Root>
        </div>

        {/* Footer Notice */}
        <div className="mt-8 bg-green-50 border border-green-200 rounded-lg p-6">
          <div className="flex items-start">
            <Shield className="w-6 h-6 text-green-600 mr-3 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="font-semibold text-green-800 mb-2">Your Privacy Rights</h3>
              <p className="text-green-700 text-sm leading-relaxed">
                You have the right to access, update, or delete your personal information at any time. We are committed to protecting your privacy and handling your data responsibly in accordance with applicable laws and regulations.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Contact Us Button */}
      <ContactUsButton />
      <Footer/>
    </div>
  );
};

export default PrivacyPolicy;
